DEFAULT_FIELDS = {
    "company": "확인 필요",
    "work_location": "확인 필요",
    "recruitment_field": "확인 필요",
    "job_grade": "확인 필요",
    "job_duty": "확인 필요",
    "headcount": "확인 필요",
    "employment_type": "확인 필요",
    "eligibility": "확인 필요",
    "preferred": "확인 필요",
    "process": "확인 필요",
    "application_period": "확인 필요",
    "application_method": "확인 필요",
    "application_url": "",
    "student_deadline_recommendation": "확인 필요",
    "required_documents": "확인 필요",
    "ai_test_notice": "확인 필요",
    "self_intro_questions": [],
    "attachments_to_forward": [],
    "exclude_attachments": [],
    "available_majors": "확인 필요",
    "missing_fields": [],
    "confidence": "확인 필요",
    "notes": "",
}

FIELD_LABELS = {
    "company": "기업체명",
    "work_location": "근무지",
    "recruitment_field": "채용 분야",
    "job_grade": "채용 직급",
    "job_duty": "채용 직무",
    "headcount": "채용인원",
    "employment_type": "고용형태",
    "eligibility": "지원 자격",
    "preferred": "우대 사항",
    "process": "채용 절차",
    "application_period": "접수 기간",
    "application_method": "접수 방법",
    "application_url": "접수 URL",
    "required_documents": "제출/증빙서류",
    "ai_test_notice": "AI전형 안내",
    "available_majors": "지원 가능 학과/전공",
    "notes": "비고",
}
